### ISSUE TITLE
Nullable `@oneOf` parameterization using variable is rejected

### ISSUE THREAD

**Issue by ornamental** [ghostdogpr/caliban#2812]
There seems to be a misinterpretation of the specification concerning passing of `@oneOf` input objects via variables.

Relevant schema excerpt:
```
enum DatabaseOwnerType {
  Organization
  Contractor
}

input DatabaseOwnershipFilterInput @oneOf {
  ownerType: DatabaseOwnerType
  contractorIds: [ID!]
}

type Database {
  id: ID!
  name: String!
}

type DatabaseCollection {
  id: ID!
  name: String!
  databases(ownership: DatabaseOwnershipFilterInput): [Database!]
}

type Queries {
  databaseCollections: [DatabaseCollection!]
}
```

The ownership argument in `databases` field is optional, so it should be possible to use a variable of (nullable) type `DatabaseOwnershipFilterInput` to parameterize a query. So
```
query($ownership: DatabaseOwnershipFilterInput) {
  databaseCollections {
    id
    name
    databases(ownership: $ownership) {
      id
      name
    }
  }
}
```
should be admissible and should accept variable sets `{"ownership": null}` and, say, `{"ownership": {"ownerType": "Contractor"}}`.

Yet it is rejected with an error: `Variable 'ownership' cannot be nullable.`
The specification does indeed prohibit nullable variables to be used to parameterize _fields_ of `@oneOf` input objects. Here, however, it is the `@oneOf` input object itself that is parameterized, not its field.

**Comment by guymers** [comment]
Can you try the latest code on `series/2.x` https://github.com/ghostdogpr/caliban/pull/2691

**Comment by ghostdogpr** [comment]
That fix was released in 2.11.0 though 🤔

**Comment by guymers** [comment]
Ahh yeah sorry ignore me

**Comment by ghostdogpr** [comment]
But it's worth checking if @ornamental is using the latest one since it sounds like the same issue.

**Comment by ornamental** [comment]
I first saw it in an earlier version, but have since re-checked with 2.11.1; the problem remains. Passing the value directly works fine, only the passing via variable is affected.

**Comment by ghostdogpr** [comment]
Closed by https://github.com/ghostdogpr/caliban/pull/2818
